### ISSUE TITLE
Plugin settings do not have controls to enable MySQL

### ISSUE THREAD

**Issue by msc-** [Xycl/plugin.image.mypicsdb#11]
I want to use a shared MySQL, having just set up my video and music databases to do so. Readme.txt says enable MySQL and enter the user & password in the plugin settings. There are no such controls in the plugin settings or they are so hidden I failed to find them.

I see 4 tabs: General, Files, Menu Items and Debugging and nothing about MySQL on any of them.

How do I enable MySQL? And as part of that, where do I enter the URL of the SQL server? That is not even mentioned in the Readme.txt.

I have version 12.3.14 running in Gotham.

BTW, why is this plugin no longer in the official XBMC repository?

**Comment by Xycl** [comment]
There those controls
