### ISSUE TITLE
Enable JSON-RPC to scan / clean database 

### ISSUE THREAD

**Issue by denics** [Xycl/plugin.image.mypicsdb#14]
Hi Guys, I am quite new to MyPicsDB but I love it! I finally found a nice workflow:
- Import and Edit photos with Shotwell / Darktable
- Rsync the photos to my pi device with
  
  `rsync -aHAXxv --numeric-ids --delete --progress --exclude RAW/ -e "ssh -T -c arcfour -o Compression=no -x" Pictures/ pi@192.168.xxx.xxx:/home/kodi/Pictures`
- Go to the interface and launch the updater

It would be nice to have the possibility to launch a curl command like for [videos and music](http://kodi.wiki/view/HOW-TO:Remotely_update_library) from the remote, to launch the scan / clean.

**Comment by t4-ravenbird** [comment]
This looks like what I suggested here : https://github.com/Xycl/script.service.mypicsdb/pull/1 ?

**Comment by denics** [comment]
Amazing! thanks. I will give it a try.

**Comment by t4-ravenbird** [comment]
You will need to modify your plugin manually - it is only a PR and not merged yet. But I take your response as support for the PR :+1:

**Comment by Xycl** [comment]
Merged
